export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_MULTIPLE_SECTION_USER_REQUEST =
  'SET_MULTIPLE_SECTION_USER_REQUEST';
export const SET_MULTIPLE_SECTION_USER_SUCCESS =
  'SET_MULTIPLE_SECTION_USER_SUCCESS';
export const SET_MULTIPLE_SECTION_USER_FAILURE =
  'SET_MULTIPLE_SECTION_USER_FAILURE';

export const LOAD_DYNAMIC_YIELD_REQUEST_ACTION =
  'LOAD_DYNAMIC_YIELD_REQUEST_ACTION';
export const LOAD_DYNAMIC_YIELD_SUCCESS_ACTION =
  'LOAD_DYNAMIC_YIELD_SUCCESS_ACTION';
export const LOAD_DYNAMIC_YIELD_FAILURE_ACTION =
  'LOAD_DYNAMIC_YIELD_FAILURE_ACTION';

export const ADD_USER_SECTION_REQUEST = 'ADD_USER_SECTION_REQUEST';
export const ADD_USER_SECTION_SUCCESS = 'ADD_USER_SECTION_SUCCESS';
export const ADD_USER_SECTION_FAILURE = 'ADD_USER_SECTION_FAILURE';

export const DEL_USER_SECTION_REQUEST = 'DEL_USER_SECTION_REQUEST';
export const DEL_USER_SECTION_SUCCESS = 'DEL_USER_SECTION_SUCCESS';
export const DEL_USER_SECTION_FAILURE = 'DEL_USER_SECTION_FAILURE';

export const UPDATE_ACTIVE_SECTION = 'UPDATE_ACTIVE_SECTION';

export const ADD_CONTEXT_ITEM_REQUEST = 'ADD_CONTEXT_ITEM_REQUEST';
export const ADD_CONTEXT_ITEM_SUCCESS = 'ADD_CONTEXT_ITEM_SUCCESS';
export const ADD_CONTEXT_ITEM_FAILURE = 'ADD_CONTEXT_ITEM_FAILURE';

export const DEL_CONTEXT_ITEM_REQUEST = 'DEL_CONTEXT_ITEM_REQUEST';
export const DEL_CONTEXT_ITEM_SUCCESS = 'DEL_CONTEXT_ITEM_SUCCESS';
export const DEL_CONTEXT_ITEM_FAILURE = 'DEL_CONTEXT_ITEM_FAILURE';
